# Generated by Django 4.1.7 on 2023-03-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
