# Generated by Django 4.1.7 on 2023-03-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_maps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maps',
            new_name='Map',
        ),
    ]
