# Generated by Django 4.1.7 on 2023-03-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_maps_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='map_description',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_img',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_name',
        ),
    ]
