# Generated by Django 4.1.7 on 2023-03-23 06:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50)),
                ('descriptiontitle', models.CharField(max_length=500)),
                ('agenttitle', models.CharField(max_length=500)),
                ('descriptionagenttitle', models.CharField(max_length=500)),
                ('maptitle', models.CharField(max_length=500)),
                ('descriptionmaptitle', models.CharField(max_length=500)),
                ('img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='img')),
            ],
            options={
                'verbose_name': 'home',
                'verbose_name_plural': 'homes',
            },
        ),
    ]
