# Generated by Django 4.1.7 on 2023-03-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_specs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specs',
            new_name='Spec',
        ),
    ]
