# Generated by Django 4.1.7 on 2023-03-23 12:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_role_alter_agent_skill_e_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='skill_c_video',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='skill_x_video',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
