# Generated by Django 4.1.7 on 2023-03-23 15:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_agent_skill_c_video_alter_agent_skill_x_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='img')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'newss',
            },
        ),
    ]
