# Generated by Django 4.1.7 on 2023-03-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
