# Generated by Django 4.1.7 on 2023-03-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_news_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='datetime',
            new_name='date',
        ),
    ]
