# Generated by Django 4.1.7 on 2023-03-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_datetime_news_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
        migrations.AddField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
