# Generated by Django 4.1.7 on 2023-03-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
