# Generated by Django 4.1.7 on 2023-03-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_news_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='fire_rate',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
