# Generated by Django 4.1.7 on 2023-03-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_weapon_fire_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='fire_rate',
        ),
    ]
