# Generated by Django 4.1.7 on 2023-03-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_weapon_fire_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='dmg_b',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='dmg_h',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='dmg_l',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
