# Generated by Django 4.1.7 on 2023-03-24 18:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_weapon_dmg_b_weapon_dmg_h_weapon_dmg_l'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='img',
            new_name='img_agent',
        ),
        migrations.RemoveField(
            model_name='home',
            name='agenttitle',
        ),
        migrations.RemoveField(
            model_name='home',
            name='descriptionagenttitle',
        ),
        migrations.RemoveField(
            model_name='home',
            name='descriptionmaptitle',
        ),
        migrations.RemoveField(
            model_name='home',
            name='descriptiontitle',
        ),
        migrations.RemoveField(
            model_name='home',
            name='maptitle',
        ),
        migrations.RemoveField(
            model_name='home',
            name='title1',
        ),
        migrations.AddField(
            model_name='home',
            name='description_agent',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='description_intro',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='description_map',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='img_intro',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='img_map',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='title_agent',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='title_intro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='title_map',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
