# Generated by Django 4.1.7 on 2023-03-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_home_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='description_agent',
        ),
        migrations.RemoveField(
            model_name='home',
            name='description_intro',
        ),
        migrations.RemoveField(
            model_name='home',
            name='description_map',
        ),
        migrations.RemoveField(
            model_name='home',
            name='img_agent',
        ),
        migrations.RemoveField(
            model_name='home',
            name='img_intro',
        ),
        migrations.RemoveField(
            model_name='home',
            name='img_map',
        ),
        migrations.RemoveField(
            model_name='home',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='home',
            name='title_agent',
        ),
        migrations.RemoveField(
            model_name='home',
            name='title_intro',
        ),
        migrations.RemoveField(
            model_name='home',
            name='title_map',
        ),
    ]
