# Generated by Django 4.1.7 on 2023-03-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_home_description_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='weapon_detail',
            new_name='type',
        ),
    ]
