# Generated by Django 4.1.7 on 2023-03-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_rename_weapon_detail_weapon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='link',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
