# Generated by Django 4.1.7 on 2023-03-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_link_home_description_agents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
