# Generated by Django 4.1.7 on 2023-03-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_news_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='title_agents',
            new_name='nav_title',
        ),
        migrations.RemoveField(
            model_name='home',
            name='description_agents',
        ),
        migrations.RemoveField(
            model_name='home',
            name='img',
        ),
        migrations.RemoveField(
            model_name='home',
            name='title',
        ),
    ]
