# Generated by Django 4.1.7 on 2023-03-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_home_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='nav_title',
            new_name='name',
        ),
    ]
