# Generated by Django 4.1.7 on 2023-03-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_home_home_agents_home_home_agents_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='home_agents',
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_agents_description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_agents_img',
        ),
    ]
