# Generated by Django 4.1.7 on 2023-03-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_home_home_agents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='skill_c_description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='agent',
            name='skill_c_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='skill_e_description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='agent',
            name='skill_e_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='skill_q_description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='agent',
            name='skill_q_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='skill_x_description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='agent',
            name='skill_x_name',
            field=models.CharField(max_length=100),
        ),
    ]
