# Generated by Django 4.1.7 on 2023-04-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_agent_skill_c_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='a_link',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='a_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
