# Generated by Django 4.1.7 on 2023-04-03 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_weapon_agent_home_weapon_agent_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='page_home',
        ),
    ]
