# Generated by Django 4.1.7 on 2023-04-03 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_weapon_page_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='agent_home',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='agent_link',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='arsenal_home',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='arsenal_link',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='map_home',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='map_link',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='news_home',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='news_link',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='page_link',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='specs_home',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='specs_link',
        ),
    ]
