# Generated by Django 4.1.7 on 2023-04-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_remove_weapon_agent_home_remove_weapon_agent_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='a_link',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='a_name',
        ),
    ]
