# Generated by Django 4.1.7 on 2023-04-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_remove_agent_a_link_remove_agent_a_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='skill_c_description',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_c_icon',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_c_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_c_video',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_e_description',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_e_icon',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_e_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_e_video',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_x_description',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_x_icon',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_x_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_x_video',
        ),
    ]
