# Generated by Django 4.1.7 on 2023-04-04 10:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_remove_agent_skill_c_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='skill_q_video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='img'),
        ),
    ]
