# Generated by Django 4.1.7 on 2023-04-04 10:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_agent_skill_q_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='skill_c_description',
            field=models.CharField(default=1, max_length=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='skill_c_icon',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='icon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='skill_c_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='skill_c_video',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='skill_e_description',
            field=models.CharField(default=1, max_length=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='skill_e_icon',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='icon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='skill_e_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='skill_e_video',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='skill_x_description',
            field=models.CharField(default=1, max_length=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='skill_x_icon',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='icon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='skill_x_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='skill_x_video',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='skill_q_video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='img'),
        ),
    ]
