# Generated by Django 4.1.7 on 2023-04-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_map_map_img1_map_map_img2_map_map_img3_map_map_img4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='map_img1',
            new_name='map_img_1',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='map_img2',
            new_name='map_img_2',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='map_img3',
            new_name='map_img_3',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='map_img4',
            new_name='map_img_4',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='map_img5',
            new_name='map_img_5',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='map_img6',
            new_name='map_img_6',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='map_img7',
            new_name='map_img_7',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='map_img8',
            new_name='map_img_8',
        ),
    ]
