# Generated by Django 4.1.7 on 2023-04-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_rename_map_img1_map_map_img_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='skill_c_description',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_c_icon',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_c_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_c_video',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_e_description',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_e_icon',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_e_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_e_video',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_q_description',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_q_icon',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_q_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_q_video',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_x_description',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_x_icon',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_x_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_x_video',
        ),
    ]
