# Generated by Django 4.1.7 on 2023-04-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_remove_agent_skill_c_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='map_img_1',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_img_2',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_img_3',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_img_4',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_img_5',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_img_6',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_img_7',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_img_8',
        ),
    ]
