# Generated by Django 4.1.7 on 2023-04-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_remove_map_map_img_1_remove_map_map_img_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
