# Generated by Django 4.1.7 on 2023-04-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_map_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='slug',
            field=models.SlugField(),
        ),
    ]
