# Generated by Django 4.1.7 on 2023-04-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_agent_skill_c_description_agent_skill_c_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
