# Generated by Django 4.1.7 on 2023-04-04 17:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_agent_country_agent_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='img_icon',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
    ]
