# Generated by Django 4.1.7 on 2023-04-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_agent_img_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='img_icon',
            new_name='role_icon',
        ),
    ]
