# Generated by Django 4.1.7 on 2023-04-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_rename_img_icon_agent_role_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='role_icon',
            new_name='roleicon',
        ),
    ]
