# Generated by Django 4.1.7 on 2023-04-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_rename_role_icon_agent_roleicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bio',
            field=models.CharField(default=2, max_length=600),
            preserve_default=False,
        ),
    ]
