# Generated by Django 4.1.7 on 2023-04-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_agent_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
