# Generated by Django 4.1.7 on 2023-04-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_remove_spec_description_remove_spec_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
