# Generated by Django 4.1.7 on 2023-04-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_spec_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='slug',
        ),
    ]
