# Generated by Django 4.1.7 on 2023-04-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_remove_spec_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
