# Generated by Django 4.1.7 on 2023-04-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='highend',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='minimum',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='recommended',
        ),
    ]
