# Generated by Django 4.1.7 on 2023-04-06 01:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_remove_spec_highend_remove_spec_minimum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
    ]
