# Generated by Django 4.1.7 on 2023-04-06 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_agent_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='avatar',
            new_name='avatar_icon',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='roleicon',
            new_name='role_icon',
        ),
    ]
