# Generated by Django 4.1.7 on 2023-04-06 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_rename_avatar_agent_avatar_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='description',
        ),
    ]
