# Generated by Django 4.1.7 on 2023-04-06 02:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_remove_agent_skill_c_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='background_img',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
    ]
