# Generated by Django 4.1.7 on 2023-04-06 02:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_agent_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='background_img',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
