# Generated by Django 4.1.7 on 2023-04-06 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_alter_agent_background_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='background_img',
        ),
    ]
