# Generated by Django 4.1.7 on 2023-04-06 11:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_agent_skill_c_video_agent_skill_e_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='skill_c_video',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='skill_e_video',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='skill_q_video',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='skill_x_video',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
