# Generated by Django 4.1.7 on 2023-04-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_alter_agent_skill_c_video_alter_agent_skill_e_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'signup',
                'verbose_name_plural': 'signups',
            },
        ),
    ]
