# Generated by Django 4.1.7 on 2023-04-06 12:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='windows',
        ),
        migrations.AddField(
            model_name='signup',
            name='img',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
    ]
