# Generated by Django 4.1.7 on 2023-04-06 13:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_remove_signup_windows_signup_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='signup',
            name='img2',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='img3',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='img4',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='img5',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='img6',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='img7',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
    ]
