# Generated by Django 4.1.7 on 2023-04-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_rename_img_signup_img1_signup_img2_signup_img3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='number',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='role_icon',
        ),
    ]
