# Generated by Django 4.1.7 on 2023-04-09 14:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_remove_agent_number_remove_agent_role_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='role_icon',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
    ]
