# Generated by Django 4.1.7 on 2023-04-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_agent_number_agent_role_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='dmg_b_far',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='dmg_h_far',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='dmg_l_far',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
