# Generated by Django 4.1.7 on 2023-04-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_weapon_dmg_b_far_weapon_dmg_h_far_weapon_dmg_l_far'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='money',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
