# Generated by Django 4.1.7 on 2023-04-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_weapon_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'premier',
                'verbose_name_plural': 'premiers',
            },
        ),
    ]
