# Generated by Django 4.1.7 on 2023-04-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_premier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premier',
            name='Name',
        ),
        migrations.AddField(
            model_name='premier',
            name='FAQ_title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premier',
            name='answer',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premier',
            name='question',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
