# Generated by Django 4.1.7 on 2023-04-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_remove_premier_name_premier_faq_title_premier_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premier',
            name='FAQ_title',
        ),
    ]
