# Generated by Django 4.1.7 on 2023-04-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_remove_premier_faq_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premier',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
    ]
