# Generated by Django 4.1.7 on 2023-04-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_alter_premier_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='img6',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='img7',
        ),
        migrations.AddField(
            model_name='signup',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
