# Generated by Django 4.1.7 on 2023-05-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_weapon_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='a',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
