# Generated by Django 4.1.7 on 2023-05-09 11:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_weapon_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='name',
            new_name='news_title',
        ),
        migrations.AddField(
            model_name='home',
            name='bp_img',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='bp_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='datetime',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='news_img',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='link',
            field=models.URLField(),
        ),
    ]
