# Generated by Django 4.1.7 on 2023-05-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_rename_name_home_news_title_home_bp_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='news_img',
            new_name='home_img',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='news_title',
            new_name='home_title',
        ),
    ]
