# Generated by Django 4.1.7 on 2023-05-09 13:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_home_a_alter_news_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='link',
            new_name='news_link',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='name',
            new_name='news_title',
        ),
        migrations.RemoveField(
            model_name='home',
            name='a',
        ),
        migrations.AddField(
            model_name='home',
            name='news_img',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
    ]
