# Generated by Django 4.1.7 on 2023-05-09 13:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_rename_link_home_news_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='bp',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='bp_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
