# Generated by Django 4.1.7 on 2023-05-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_rename_news_img_home_home_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='home_img',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_title',
        ),
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
