# Generated by Django 4.1.7 on 2023-05-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_rename_home_img_home_img_remove_home_home_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='datetime',
        ),
    ]
