# Generated by Django 4.1.7 on 2023-05-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_home_bp_home_bp_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='news_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='bp_title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='home',
            name='news_img',
        ),
        migrations.RemoveField(
            model_name='home',
            name='news_title',
        ),
    ]
