# Generated by Django 4.1.7 on 2023-05-09 13:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0095_rename_news_link_home_link_rename_bp_title_home_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='img',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
    ]
