# Generated by Django 4.1.7 on 2023-05-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0096_rename_title_home_name_home_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='datetime',
        ),
    ]
