# Generated by Django 4.1.7 on 2023-05-09 13:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0096_home_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='bp_img',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
    ]
