# Generated by Django 4.1.7 on 2023-05-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_remove_home_bp_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battlepass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('datetiem', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'battlepass',
                'verbose_name_plural': 'battlepasss',
            },
        ),
    ]
