# Generated by Django 4.1.7 on 2023-05-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_remove_home_bp_img_remove_home_bp_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='datetime',
        ),
    ]
