# Generated by Django 4.1.7 on 2023-05-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0099_battlepass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlepass',
            old_name='datetiem',
            new_name='datetime',
        ),
        migrations.AddField(
            model_name='battlepass',
            name='bio',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
