# Generated by Django 4.1.7 on 2023-05-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0099_remove_news_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
