# Generated by Django 4.1.7 on 2023-05-30 05:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_rename_datetiem_battlepass_datetime_battlepass_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlepass',
            name='img',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='img'),
            preserve_default=False,
        ),
    ]
