# Generated by Django 4.1.7 on 2023-05-31 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_remove_battlepass_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlepass',
            old_name='bio',
            new_name='description',
        ),
    ]
