# Generated by Django 4.1.7 on 2023-06-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0103_rename_bio_battlepass_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
