# Generated by Django 4.2.1 on 2023-08-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0104_alter_news_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='gpu_4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
