# Generated by Django 4.2.1 on 2023-10-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0105_spec_gpu_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='gpu_4',
        ),
    ]
