# Generated by Django 4.1.13 on 2024-03-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0106_remove_spec_gpu_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
