# Generated by Django 4.1.13 on 2024-03-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0108_remove_home_description_home_act_home_episode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=1000)),
                ('detail_header', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'gameupdate',
                'verbose_name_plural': 'gameupdates',
            },
        ),
    ]
