# Generated by Django 4.1.13 on 2024-03-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0109_gameupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameupdate',
            name='big_title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameupdate',
            name='smail_detail',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameupdate',
            name='title',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
