# Generated by Django 4.1.13 on 2024-03-26 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0110_gameupdate_big_title_gameupdate_smail_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameupdate',
            name='detail_header',
        ),
        migrations.RemoveField(
            model_name='gameupdate',
            name='header',
        ),
    ]
