# Generated by Django 4.1.13 on 2024-03-26 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0111_remove_gameupdate_detail_header_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameupdate',
            old_name='smail_detail',
            new_name='small_detail',
        ),
    ]
