# Generated by Django 4.1.13 on 2024-03-26 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0113_rename_small_detail_gameupdate_small_detail_0_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameupdate',
            name='small_detail_0',
        ),
        migrations.RemoveField(
            model_name='gameupdate',
            name='small_detail_2',
        ),
        migrations.RemoveField(
            model_name='gameupdate',
            name='small_detail_3',
        ),
        migrations.RemoveField(
            model_name='gameupdate',
            name='small_detail_4',
        ),
        migrations.RemoveField(
            model_name='gameupdate',
            name='small_detail_5',
        ),
        migrations.RemoveField(
            model_name='gameupdate',
            name='small_detail_6',
        ),
        migrations.RemoveField(
            model_name='gameupdate',
            name='small_detail_7',
        ),
        migrations.RemoveField(
            model_name='gameupdate',
            name='small_detail_8',
        ),
        migrations.RemoveField(
            model_name='gameupdate',
            name='small_detail_9',
        ),
    ]
