# Generated by Django 4.1.13 on 2024-03-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0114_remove_gameupdate_small_detail_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameupdate',
            name='field3',
            field=models.IntegerField(default=0),
        ),
    ]
