# Generated by Django 4.1.13 on 2024-03-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0115_gameupdate_field3'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameupdate',
            name='field2',
            field=models.TextField(default='\n        This is a long description of field2.\n        It spans multiple lines.\n        You can include line breaks freely here.\n    '),
        ),
    ]
