# Generated by Django 4.1.13 on 2024-03-26 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0117_alter_gameupdate_field2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameupdate',
            name='field3',
        ),
        migrations.RemoveField(
            model_name='gameupdate',
            name='small_detail_1',
        ),
    ]
