# Generated by Django 4.1.13 on 2024-05-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0118_remove_gameupdate_field3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='Agent',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='arresnals',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='battlepass',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='maps',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='news',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='premieres',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='specs',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='tutorials',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
