# Generated by Django 4.1.13 on 2024-05-08 03:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0119_home_agent_home_arresnals_home_battlepass_home_maps_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='Agent',
            new_name='agent',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
