# Generated by Django 4.1.13 on 2024-05-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0121_map_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='status',
            field=models.CharField(max_length=400),
        ),
    ]
