# Generated by Django 4.1.13 on 2024-05-18 07:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0122_alter_map_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='video',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
